project:
  type: website
  output-dir: _site

website:
  title: "Yuchi Liu"
  site-url: "https://www.liuyuchi.me"
  navbar:
    pinned: true
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: Projects
        href: projects.qmd
      - text: Contact
        href: contact.qmd
  page-footer:
    center: "© Yuchi Liu. All rights reserved."

format:
  html:
    theme: cosmo
    toc: false
    css: styles.css
    include-after-body: assets/js/carousel.js
    smooth-scroll: true
