project:
  type: website

website:
  title: "Yuchi Liu"
  site-url: "https://www.liuyuchi.me"
  navbar:
    background: white
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: projects.qmd
        text: Projects
      - href: contact.qmd
        text: Contact
  page-footer:
    left: "© Yuchi Liu"
    right: "Built with Quarto"
  search: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
    link-external-newwindow: true
    page-layout: full

execute:
  freeze: auto
